pipeline {
    agent any

    options {
        skipDefaultCheckout(true)
    }

    environment {
        APP_NAME = 'GradeBookApp'
        APP_VERSION = '1.0.0'
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/jais-shaurya/jenkins-lab-assessment.git'
            }
        }

        stage('Show App Info') {
            steps {
                echo "Building ${env.APP_NAME}, version ${env.APP_VERSION}"
            }
        }

        stage('Build') {
            steps {
                dir('project5-custom-environment') {
                    bat 'python -m py_compile app.py'
                }

                echo "${env.APP_NAME} version ${env.APP_VERSION} compiled successfully."
            }
        }
    }

    post {
        success {
            echo 'Project 5 pipeline completed successfully.'
        }

        failure {
            echo 'Project 5 pipeline failed.'
        }
    }
}