pipeline {
    agent any

    options {
        skipDefaultCheckout(true)
    }

    parameters {
        booleanParam(
            name: 'RUN_EXTRA_CHECK',
            defaultValue: true,
            description: 'Run the extra application check'
        )
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/jais-shaurya/jenkins-lab-assessment.git'
            }
        }

        stage('Build') {
            steps {
                dir('project4-conditional-stage') {
                    bat 'python -m py_compile app.py'
                }

                echo 'Build successful: app.py compiled with no syntax errors.'
            }
        }

        stage('Extra Check') {
            when {
                expression {
                    return params.RUN_EXTRA_CHECK
                }
            }

            steps {
                dir('project4-conditional-stage') {
                    echo 'Running extra check: verifying greet() output format...'

                    bat '''
                        python -c "from app import greet; result=greet('Student'); assert result == 'Hello, Student'; print(result)"
                    '''
                }
            }
        }
    }

    post {
        success {
            echo 'Project 4 pipeline completed successfully.'
        }

        failure {
            echo 'Project 4 pipeline failed.'
        }
    }
}